### ISSUE TITLE
Desired feature- line chart

### ISSUE THREAD

**Issue by jhoring** [JGCRI/GCAM-dashboard#3]

**Comment by rplzzz** [comment]
I will need to get a little more information about what kind of line chart we're looking for in order to tackle this one.  Adding a line chart tab is easy enough, but any of the obvious ways to do it would be redundant with the bar chart.

**Comment by rplzzz** [comment]
Lacking any specific feedback on what we are looking for here, I'm going to close this out.  We should have some new users coming on shortly, and I expect we'll get some good ideas for new features from them.
